export WEBCONSOLE_HOSTNAME="webconsole"
export WEBCONSOLE_SSHD_HOSTNAME="webconsole-sshd"
export WEBCONSOLE_NODESTATIC_HOSTNAME="webconsole-nodestatic"
export SSH_USER_ID=10001
export WEBCONSOLE_WETTY_PORT=3000
export WEBCONSOLE_NODESTATIC_PORT=3001
